### ISSUE TITLE
Toggle external-open not working on Mac?

### ISSUE THREAD

**Issue by alex-kovac** [sveale/external-open#1]
Nice package! 
Toggling external-open from menu, or pressing ctrl+Alt+o on Mac doesn't do much. Is this by design?
(when I add extensions to external-open settings panel, they open straight away. That part works...)

**Comment by sveale** [comment]
Thanks! 
Well, the reason that action is there is mainly because it is added by default when creating a new package :).
I suppose it could implement a toggle functionality (ie. external-open is turned on/off), but I think this is better handled by the default Atom triggers in the settings window. 
If you have any suggestions or thoughts on what it could/should do, or if it should be removed completely, it greatly apprecate it

**Comment by alex-kovac** [comment]
Speaking from my perspective (i.e. a very narrow perspective)... I initially felt/expected the following: 
- Selecting a file in the tree would open the files in Atom's tabs, as usual. 
- Selecting a file in the tree and hitting ctrl+Alt+o would open them in external editor, as defined in -external open.
  In that sense, ctrl+Alt+o command could be seen as explicit "open in external editor" command.

**Comment by sveale** [comment]
I've updated the package with some changes:
- I've removed the toggle functionality
- Right clicking in tree view allows you to open up any file in default external program
- The currently open file can be opened in the default external program by selecting 'External Open: File' from the command palette
- Updated key shortcut to execute aforementioned 'External Open: File' on currently selected file. cmd-shift-o on mac, ctrl-shift-o on win32/linux.

If you don't want any files to default open in external program, you can remove all extensions from the package settings. 
Feedback is more than welcome :)

**Comment by alex-kovac** [comment]
Great work. Feels much better! :) Here are my notes:
- external-open on preferences tab creates an error. ;) I know, no sense in externally editing the Preferences, still, Preferences tab could maybe ignore the command. For convenience, this was submitted here as issue, too...
- I cannot open a file externally using the menu command. Keystroke works fine, though.
- I cannot seem to open the file that is currently selected in the tree using the keystroke, unless I first select the file in the tree view and then click into the content of the file (as to position the cursor in it) on the work area tab. This last click feels like a click too much. (lazy me)
- The menu entry "File" is slightly too ambiguous. Maybe this is because only a noun is used. It lacks the action "part" -- the verb. Perhaps "Open in external editor" or "Open file" would be more understandable?

I hope this makes any sense to you.
Cheers.

**Comment by sveale** [comment]
- If you want to open a file from the tree view externally, and it does not have an extension that should by default be opened externally, you need to right click it and select external open. 
  - I agree that "File" is a bit amgibuous and changed it.

I'll respond to the pref tab issue in the other issue you created :)
