### ISSUE TITLE
Failing to open files in preferences

### ISSUE THREAD

**Issue by rm-code** [sveale/external-open#5]
I added .md files to be always opened in an external application. Now when I click on the "License" or "Changelog" buttons in the package preferences menu a new tab opens saying "Please wait", but it never opens the file.

Best wishes,
Robert

**Comment by sveale** [comment]
I can fix this issue, but the thing is, this isn't a "regular" opening of a file.
The URI you're trying to open up is actually something along the lines of "markdown-preview:///path/to/file", ie. it should be explicitly opened using the markdown preview plugin.

To get around this issue, and allow both use cases, I've added a configuration option ("Disregard protocol portion of URI to open"). Set this to true if you want "Licence" or "Changelog" buttons to open the file externally. If this is left unchecked, clicking these buttons will open the files up using the markdown-preview plugin.

**Comment by rm-code** [comment]
Thanks! Works like a charm :+1:
