### ISSUE TITLE
Stuck on "Open in external program"

### ISSUE THREAD

**Issue by rm-code** [sveale/external-open#6]
Okay this is a strange one. I updated to Atom version 1.0.4 this morning and now the plugin sometimes gets stuck on "Please wait - Opening in external program" tab. I say sometimes, because it does work for some of my files, but not all of them (I use the plugin only for .md files).

Will try to see if I can give you more information about when it happens.

**Comment by rm-code** [comment]
As far as I can tell it seems to be project specific, because it works on some projects, but not on others. The only difference I can see between those projects is that some of them have whitespace in their path (e.g.: `users/foo/bar/some foldername with whitespace/project`).

When I use the context menu option "Open in default program" it seems to work fine though.

**Comment by sveale** [comment]
Should be resolved in external-open@v0.6.1. Give it a go and let me know :)

The bug appeared because of the changes in relation to issue #5 .

**Comment by rm-code** [comment]
Yes, seems to be fixed in 0.6.1! Thanks :+1:
